spring:
  application:
    name: config-git
  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
server:
  port: 12000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
